export { HomeCTA } from '@components/home/call-to-actions'
export { HomeFeatures } from '@components/home/features'
export { HomeHero } from '@components/home/hero'
export { HomeQuickForm } from '@components/home/quick-form'
export { HomeReviews } from '@components/home/reviews'
export { HomeScreens } from '@components/home/screens'
export { HomeVillain } from '@components/home/villain'
